name: Deploy to Server

on:
  push:
    branches:
      - master  # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # SSH into the server and perform necessary actions
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}  # Your server's IP address
          username: ${{ secrets.SERVER_USER }}  # The SSH username (e.g., ubuntu)
          key: ${{ secrets.SERVER_SSH_KEY }}  # The private SSH key
          port: 22  # The default SSH port, can be changed if needed
          script: |
            # Navigate to the project directory
            cd /echoe5
            # Pull the latest changes from Git
            git pull origin master

            # (Optional) Install dependencies, if needed
          name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pipinstall -r requirements.txt

            # Restart the service (modify as needed based on your stack)
            sudo systemctl restart apache2  # Replace 'your-service' with the actual service name

            # (Optional) Check for errors or output logs
            # tail -n 10 /path/to/log/file.log  # If your application has a log file
